from solution import TicTacToeBoard

board = TicTacToeBoard()
board.get_field()
board.make_move(1, 1)
board.get_field()
board.make_move(1, 1)
board.get_field()
board.make_move(1, 2)
board.get_field()
board.make_move(2, 1)
board.make_move(2, 2)
board.make_move(3, 1)
board.make_move(2, 2)
board.get_field()
board.new_game()